version: "2.1"

volumes:
  proxy:
  certs:
  db:
  jellyfin-config:
  jellyfin-cache:
  media:
  jellyfin-lib:
  portal:
  portal-config:

services:
  # https://hub.docker.com/r/jc21/nginx-proxy-manager/
  proxy:
    build: proxy
    network_mode: host
    volumes:
      - proxy:/data
      - certs:/etc/letsencrypt
    depends_on:
      - db

  # https://hub.docker.com/_/mariadb/
  db:
    image: arm64v8/mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    ports:
      - '3306:3306'
  # https://hub.docker.com/r/jc21/nginx-proxy-manager/
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - 82:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
        - jellyfin-config:/config
        - jellyfin-cache:/cache
        - media:/media
        - jellyfin-lib:/opt/vc/lib
    environment:
        PUID: 1000
        PGID: 1000
        JELLYFIN_PublishedServerUrl: flix.com
    devices:
      - /dev/vchiq:/dev/vchiq #hardware acceleration for Rasp 3 e 4
      # - /dev/vcsm:/dev/vcsm #hardware acceleration for Rasp 3
  # https://hub.docker.com/r/filebrowser/filebrowser
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 83:80
    volumes:
      - media:/srv
    environment:
      PGID: 1000
      PUID: 1000
    command: -- c
  # https://hub.docker.com/r/linuxserver/code-server
  code:
    image: ghcr.io/linuxserver/code-server
    ports:
      - 84:8443
    restart: unless-stopped
    volumes:
      - portal-config:/config
      - portal:/config/workspace
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Brasil
      PASSWORD: admin
      PROXY_DOMAIN: code.psp.app.br
  # https://hub.docker.com/r/communityfirst/portal-dev
  portal:
    image: communityfirst/portal-dev
    ports:
      - 85:3000
    restart: unless-stopped
    volumes:
      - portal:/usr/src/nuxt-app
  # https://hub.docker.com/r/alexta69/metube
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - 86:8081
    volumes:
      - media:/downloads
    environment:
      DOWNLOAD_DIR: /downloads/metube-video
      AUDIO_DOWNLOAD_DIR: /downloads/metube-audio
