version: "2.1"

volumes:
  proxy:
  certs:
  db:
  jellyfin-config:
  jellyfin-cache:
  media:
  jellyfin-lib:
  portal:
  portal-config:
  nginx-conf:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    network_mode: host
    ports:
      - 80:80
      - 443:443
    environment:
      DEFAULT_HOST: psp.app.br
      DOCKER_HOST: /tmp/docker.sock
    volumes:
      - media:/etc/nginx/certs
      - nginx-conf:/etc/nginx
    restart: always
    labels:
      io.resin.features.balena-socket: '1'


  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - 82:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
        - jellyfin-config:/config
        - jellyfin-cache:/cache
        - media:/media
        - jellyfin-lib:/opt/vc/lib
    environment:
        PUID: 1000
        PGID: 1000
        JELLYFIN_PublishedServerUrl: flix.psp.app.br
        VIRTUAL_HOST: flix.psp.app.br
        VIRTUAL_PORT: 82
    devices:
      - /dev/vchiq:/dev/vchiq #hardware acceleration for Rasp 3 e 4
      #  - /dev/vcsm:/dev/vcsm #hardware acceleration for Rasp 3
  
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 83:80
    volumes:
      - media:/srv
    environment:
      PGID: 1000
      PUID: 1000
      VIRTUAL_HOST: pasta.psp.app.br
      VIRTUAL_PORT: 83
    command: -- c
    
  code:
    image: ghcr.io/linuxserver/code-server
    ports:
      - 84:8443
    restart: unless-stopped
    volumes:
      - portal-config:/config
      - portal:/config/workspace
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Brasil
      PASSWORD: jurubeba
      VIRTUAL_HOST: code.psp.app.br
      VIRTUAL_PORT: 84

  portal:
    image: communityfirst/portal-dev
    ports:
      - 85:3000
    restart: unless-stopped
    volumes:
      - portal:/usr/src/nuxt-app
    environment:
     VIRTUAL_HOST: psp.app.br
     VIRTUAL_PORT: 85
  
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - 86:8081
    volumes:
      - media:/downloads
    environment:
      DOWNLOAD_DIR: /downloads/metube-video
      AUDIO_DOWNLOAD_DIR: /downloads/metube-audio
      VIRTUAL_HOST: dl.psp.app.br
      VIRTUAL_PORT: 86
